--
-- Author: Han 
-- Date: 2015-05-06 20:36:39
--

--[[
	协议相关
]]

--------------------------------------------------------
-- 消息ID定义
--------------------------------------------------------
ID_REQ 	=	0x01000000		-- 请求

ID_ACK 	=	0x02000000		-- 应答

ID_NTF 	= 	0x04000000		-- 通知


ID_BASE_OUTER_ENTITY = 0x00006000 -- 业务服务器消息ID

MSGID_OUTER_SYSTEM 	= 0x00008000 -- 系统消息ID

MSGID_OUTER_GAME  = 0x00010000 -- 游戏中的消息ID


--[[ http 服务器消息 ]]

MSGID_REGISTER_GUEST        =  MSGID_OUTER_SYSTEM + 101         --游客注册     
MSGID_LOGIN_GUEST 			=  MSGID_OUTER_SYSTEM + 102	  	    --游客登陆		
MSGID_REGISTER_USER         =  MSGID_OUTER_SYSTEM + 103         --用户注册     
MSGID_LOGIN_USER            =  MSGID_OUTER_SYSTEM + 104         --用户登录     
MSGID_GETVERIFYCODE_USER    =  MSGID_OUTER_SYSTEM + 105         --获取手机验证码 
MSGID_RESETPASSWD_USER      =  MSGID_OUTER_SYSTEM + 106         --找回密码
MSGID_GETORDER              =  MSGID_OUTER_SYSTEM + 107         --获取订单
MSGID_DELIVER               =  MSGID_OUTER_SYSTEM + 108         --请求发货
MSGID_GETPACKAGEINFO        =  MSGID_OUTER_SYSTEM + 109         --获取背包信息


--【【业务服务器消息ID】】

--升级用户
MSGID_SYS_UPGRADE_GUEST   =   ID_BASE_OUTER_ENTITY + 1
 --修改用户信息
MSGID_SYS_MODIFY_USERINFO =   ID_BASE_OUTER_ENTITY + 2
 --绑定手机
MSGID_SYS_BIND_MOBILE     =   ID_BASE_OUTER_ENTITY + 3
 --解绑手机
MSGID_SYS_UNBIND_MOBILE   =   ID_BASE_OUTER_ENTITY + 4
 --系统广播
MSGID_SYS_BROADCAST       =   ID_BASE_OUTER_ENTITY + 5
 --进入保险箱
MSGID_SYS_SAFEBOX_ENTER   =   ID_BASE_OUTER_ENTITY + 6
 --保险箱金币操作
MSGID_SYS_SAFEBOX_OPERATECOINS = ID_BASE_OUTER_ENTITY + 7
 --保险箱历史记录
MSGID_SYS_SAFEBOX_HISTORY      = ID_BASE_OUTER_ENTITY + 8
 --找回保险箱密码
MSGID_SYS_SAFEBOX_RESETPASSWD  = ID_BASE_OUTER_ENTITY + 9
 --修改保险箱密码
MSGID_SYS_SAFEBOX_MODIFYPASSWD = ID_BASE_OUTER_ENTITY + 10
--背包
MSGID_SYS_PACKAGE    = ID_BASE_OUTER_ENTITY + 11
--金币免充
MSGID_SYS_FREECHARGE = ID_BASE_OUTER_ENTITY + 12

--【【系统消息ID】】

--保持连接
MSGID_SYS_HOLD = MSGID_OUTER_SYSTEM  + 1
--登录
MSGID_SYS_LOGINHALL =  MSGID_OUTER_SYSTEM  + 2
--配桌
MSGID_SYS_QUICK_START = MSGID_OUTER_SYSTEM  + 3
 --加入桌子
MSGID_SYS_JOIN_TABLE = MSGID_OUTER_SYSTEM  + 4
 ---坐下
MSGID_SYS_SIT_DOWN =  MSGID_OUTER_SYSTEM + 5
 ---准备
MSGID_SYS_READY = MSGID_OUTER_SYSTEM + 6
--取消准备  
MSGID_SYS_CANCEL_READY = MSGID_OUTER_SYSTEM + 7

MSGID_SYS_STAND_UP = MSGID_OUTER_SYSTEM + 8
 --离开
MSGID_SYS_LEAVE_TABLE = MSGID_OUTER_SYSTEM + 9
--桌子事件 
MSGID_SYS_TABLE_EVENT = MSGID_OUTER_SYSTEM + 10

MSGID_SYS_MULTIPLE_LOGIN =  MSGID_OUTER_SYSTEM + 11


 --【【游戏中的消息ID】】

 --申请上庄
 MSGID_JOIN_BANKER =  MSGID_OUTER_GAME + 1   --65537
 --下注
 MSGID_JOIN_COINS =  MSGID_OUTER_GAME + 2    --65538
 --聊天      
 MSGID_CHAT =  MSGID_OUTER_GAME + 3
 --通知游戏状态       
 MSGID_STATUS =  MSGID_OUTER_GAME + 4
 --换庄       
 MSGID_CHANGE_BANKER = MSGID_OUTER_GAME + 5
 --通知游戏结果       
 MSGID_RESULT =  MSGID_OUTER_GAME + 6
 --通知玩家当前桌面信息         
 MSGID_BOARD_INFO =  MSGID_OUTER_GAME + 7
 --红包
 MSGID_GIFT_GRAB = MSGID_OUTER_GAME + 8
 --系统消息
 MSGID_CHAT_SYSTEM = MSGID_OUTER_GAME + 9
 --玩家列表
 MSGID_PLAYER_LIST = MSGID_OUTER_GAME + 10
 --取消上庄
 MSGID_QUIT_BANKER =  MSGID_OUTER_GAME + 11
 --通知玩家金币变化
 MSGID_MONEY_CHG =  MSGID_OUTER_GAME + 12









